import Chance from 'chance';

const chance = new Chance();

export default {
  'room.1': {
    id: 'room.1',
    name: 'Hallway, Start',
    description: chance.paragraph(),
    exits: { s: 'room.2', e: 'room.3', w: 'room.4', d: 'room.down' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.down': {
    id: 'room.down',
    name: 'Downstairs',
    description: chance.paragraph(),
    exits: { u: 'room.1' },
    depth: 0,
    items: [],
    units: [],
  },
  'room.2': {
    id: 'room.2',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.1', s: 'room.5' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.3': {
    id: 'room.3',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { w: 'room.1', ne: 'room.6' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.4': {
    id: 'room.4',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { e: 'room.1', nw: 'room.7' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.5': {
    id: 'room.5',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.2', s: 'room.10', w: 'room.8', e: 'room.9' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.6': {
    id: 'room.6',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { sw: 'room.3', n: 'room.6n' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.6n': {
    id: 'room.6n',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { s: 'room.6', n: 'room.6nn' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.6nn': {
    id: 'room.6nn',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { s: 'room.6n', nw: 'room.6nw' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.6nw': {
    id: 'room.6nw',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { se: 'room.6nn', w: 'room.6n3' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.6n3': {
    id: 'room.6n3',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { e: 'room.6nw', w: 'room.6w2' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.6w2': {
    id: 'room.6w2',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { e: 'room.6n3', sw: 'room.6w1' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.6w1': {
    id: 'room.6w1',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { ne: 'room.6w2', s: 'room.6w' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.6w': {
    id: 'room.6w',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.6w1', s: 'room.7' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.7': {
    id: 'room.7',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { se: 'room.4', n: 'room.6w' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.8': {
    id: 'room.8',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { e: 'room.5', w: 'room.15' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.9': {
    id: 'room.9',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { w: 'room.5' },
    depth: 1,
    items: [],
    units: [],
    spawn: new Date().getTime(),
    respawn: '1d5000+1000',
    spawnlings: {
      num: '1d2+1',
      templates: ['blueprint.rat', 'blueprint.cavebear'],
    },
  },
  'room.10': {
    id: 'room.10',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.5', s: 'room.11' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.11': {
    id: 'room.11',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.10', s: 'room.12', w: 'room.13' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.12': {
    id: 'room.12',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.11', w: 'room.14' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.13': {
    id: 'room.13',
    name: 'Kitchen',
    description: chance.paragraph(),
    exits: { e: 'room.11' },
    shop: 'shop.general',
    depth: 1,
    items: [],
    units: [],
  },
  'room.14': {
    id: 'room.14',
    name: 'Reception Hall',
    description: chance.paragraph(),
    exits: { e: 'room.12' },
    trainer: 'trainer.universal',
    depth: 1,
    items: [],
    units: [],
  },
  'room.15': {
    id: 'room.15',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { e: 'room.8', w: 'room.16' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.16': {
    id: 'room.16',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { e: 'room.15', w: 'room.17' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.17': {
    id: 'room.17',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { e: 'room.16', s: 'room.18' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.18': {
    id: 'room.18',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.17', s: 'room.19' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.19': {
    id: 'room.19',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.18', s: 'room.20' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.20': {
    id: 'room.20',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.19', s: 'room.21' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.21': {
    id: 'room.21',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { n: 'room.20', e: 'room.22' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.22': {
    id: 'room.22',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { w: 'room.21', se: 'room.23' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.23': {
    id: 'room.23',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { nw: 'room.22', e: 'room.24' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.24': {
    id: 'room.24',
    name: 'Hallway, Center',
    description: chance.paragraph(),
    exits: { w: 'room.23' },
    depth: 1,
    items: [],
    units: [],
  },
};
