export default {
  'room.1': {
    id: 'room.1',
    name: 'Firebend, Dirt Entrance',
    description: '',
    exits: { n: 'room.2' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.2': {
    id: 'room.2',
    name: 'Firebend, Dirt Pathway',
    description: '',
    exits: { s: 'room.1', n: 'room.3', e: 'room.4', w: 'room.5' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.3': {
    id: 'room.3',
    name: 'Firebend, Blah Blah',
    description: '',
    exits: { s: 'room.2' },
    depth: 2,
    items: [],
    units: [],
  },
  'room.4': {
    id: 'room.4',
    name: 'Firebend, Dirt Pathway',
    description: '',
    exits: { w: 'room.2' },
    depth: 1,
    items: [],
    units: [],
  },
  'room.5': {
    id: 'room.5',
    name: 'Firebend, Dirt Pathway',
    description: '',
    exits: { e: 'room.2' },
    depth: 1,
    items: [],
    units: [],
  },
};
