module.exports = {
  code: 'roar',
  name: 'PrimalRoar',
  description: 'Unleash a thunderous roar that frightens nearby enemies and bolsters your ferocity',
  message: '{actor.name} {bellow} a thunderous roar!',
  style: 'gesture',
  target: 'self',
  speed: 100,
  cooldown: 30000,
  affect: { ma: -5 },
  pipeline: [
    {
      action: 'effect',
      target: 'self',
      style: 'debuff',
      status: 'buffed',
      duration: 15000,
      effect: { str: 5, dex: 5 },
      message: 'You are enraged!',
      cooloff: 'You calm down',
    },
    {
      action: 'effect',
      target: 'enemies',
      style: 'debuff',
      status: 'negative',
      duration: 15000,
      effect: { str: -5, dex: -5 },
      message: 'You are frightened!',
      cooloff: 'You are no longer frightened',
    },
  ],
};
