module.exports = {
  'user.1': {
    id: 1,
    room: 1,
    name: 'chardy',
  },
  'room.1': {
    id: 1,
    name: 'Town Square',
    description: 'People all come to gather, socialize, and have fun',
    exits: { n: 2, s: 3, e: 4, w: 5, ne: 7 },
  },
  'room.2': {
    id: 2,
    name: 'Bakery Shop',
    description: 'The best damn goodies you ever saw',
    exits: { s: 1 },
  },
  'room.3': {
    id: 3,
    name: 'Bank of Atlanta',
    description: 'Deposit money, make little interest',
    exits: { n: 1 },
    items: [1],
  },
  'room.4': {
    id: 4,
    name: 'Weapon Shop',
    description: 'Buy stuff for your expeditions',
    exits: { w: 1 },
  },
  'room.5': {
    id: 5,
    name: 'Magic Shop',
    description: 'Buy spells here',
    exits: { e: 1, w: { 6: [1] } },
  },
  'room.6': {
    id: 6,
    name: 'Secret Shop',
    description: 'Super secret stuff here',
    exits: { e: { 5: [1] } },
    items: [3, 2],
  },
  'room.7': {
    id: 7,
    name: 'Path of sorts',
    description: 'A path leading out of town',
    exits: { sw: 1, ne: 8 },
  },
  'room.8': {
    id: 8,
    name: 'Gates',
    description: 'Gate leading out of town',
    exits: { sw: 7, ne: { 9: [2] } },
  },
  'room.9': {
    id: 9,
    name: 'Forest',
    description: 'A scary place',
    exits: { sw: 8 },
  },
  'obstacle.1': {
    id: 1,
    type: 'door',
    state: { open: false, locked: true },
  },
  'obstacle.2': {
    id: 2,
    type: 'door',
    state: { open: false, locked: true },
  },
  'obstacle.3': {
    id: 3,
    type: 'compound',
    refs: [1],
  },
  // 'lock.1': {
  //   id: 1,
  // },
  // 'door.1': {
  //   id: 1,
  //   locks: [1],
  // },
  'item.1': {
    id: 1,
    type: 'key',
    name: 'shiny key',
    description: 'A beautiful key',
    obstacles: [1],
  },
  'item.2': {
    id: 2,
    type: 'weapon',
    name: 'axe',
    description: 'A beautiful axe',
  },
  'item.3': {
    id: 3,
    type: 'key',
    name: 'rusty key',
    description: 'A beautiful key',
    obstacles: [2],
  },
};
