module.exports = {
  'user.1': {
    id: 1,
    room: 11,
    name: 'chardy',
  },
  'room.1': {
    id: 1,
    name: 'Building Floor 5 Hallway, Apartment 528',
    description: 'People all come to gather, socialize, and have fun',
    exits: { n: 2, e: { 12: [1] } },
  },
  'room.2': {
    id: 2,
    name: 'Building Floor 5 Hallway, Apartment 526',
    description: 'The best damn goodies you ever saw',
    exits: { s: 1, w: 3, e: { 12: [2] } },
  },
  'room.3': {
    id: 3,
    name: 'Building Floor 5 Hallway',
    description: 'Deposit money, make little interest',
    exits: { e: 2, w: 4 },
  },
  'room.4': {
    id: 4,
    name: 'Building Floor 5 Hallway',
    description: 'Buy stuff for your expeditions',
    exits: { e: 3, s: 5 },
  },
  'room.5': {
    id: 5,
    name: 'Building Floor 5, Elevator Lobby',
    description: 'Buy spells here',
    exits: { n: 4, e: 6 },
  },
  'room.6': {
    id: 6,
    name: 'Building Floor 5, Elevator',
    description: 'You hear the sound of the elevator bell; the doors open to the west',
    exits: { w: 5, d: 44 },
  },
  'room.44': {
    id: 44,
    name: 'Building Floor 4, Elevator',
    description: 'Buy spells here',
    exits: { d: 43, u: 6 },
  },
  'room.43': {
    id: 43,
    name: 'Building Floor 3, Elevator',
    description: 'Buy spells here',
    exits: { d: 42, u: 44 },
  },
  'room.42': {
    id: 42,
    name: 'Building Floor 2, Elevator',
    description: 'Buy spells here',
    exits: { d: 7, u: 43 },
  },
  'room.7': {
    id: 7,
    name: 'Building Floor 1, Elevator',
    description: 'Buy spells here',
    exits: { w: 8, u: 42 },
  },
  'room.8': {
    id: 8,
    name: 'Building Floor 1, Elevator Lobby',
    description: 'Gate leading out of town',
    exits: { w: 9, e: 7 },
  },
  'room.9': {
    id: 9,
    name: 'Parking Garage, Building Entrance',
    description: 'A scary place',
    exits: { e: 8, n: 10 },
  },
  'room.10': {
    id: 10,
    name: 'Parking Garage',
    description: 'A scary place',
    exits: { n: 11, s: 9 },
  },
  'room.11': {
    id: 11,
    name: 'Parking Garage, Christie\'s Parking Spot',
    description: 'A scary place',
    exits: { s: 10 },
  },
  'obstacle.1': {
    id: 1,
    type: 'door',
    name: 'door',
    state: { open: false, locked: true },
  },
  'obstacle.2': {
    id: 2,
    type: 'door',
    name: 'door',
    state: { open: false, locked: true },
  },
  'obstacle.3': {
    id: 3,
    type: 'button',
    name: 'elevator button',
    state: { pushed: false },
    effect: {
      navigate: { to: 1 },
      feedback: 'You are teleported elsewhere',
    },
  },
  'obstacle.10': {
    id: 10,
    type: 'compound',
    refs: [1],
    state: {},
  },
  'item.1': {
    id: 1,
    type: 'key',
    name: 'set of keys',
    description: 'A beautiful key',
    obstacles: [1],
    state: { hidden: true },
  },
  'item.2': {
    id: 2,
    type: 'general',
    name: 'rope',
    description: 'A beautiful rope',
    obstacles: [2],
    state: { hidden: true },
  },
  'item.3': {
    id: 3,
    type: 'general',
    name: 'water bottle',
    description: 'A beautiful water bottle',
    state: {},
  },
  'storyline.1': {
    id: 1,
    repeat: 0,
    sequence: [
      { type: 'info', message: 'You come there' },
      {
        type: 'query',
        message: 'What now!?',
        response: {
        },
      },
    ],
  },
};
